### ISSUE TITLE
SchemaConfigured try to set defaults for readonly fields (nti.schema-1.1.3)

### ISSUE THREAD

**Issue by papachoco** [NextThought/nti.schema#11]
in SchemaConfigured mixin class 

The following code is executed
```python
 for f, fields in _iteritems(schema):
          if not hasattr(self, f):
              setattr(self, f, fields.default)
```
We are getting a "AttributeError: can't set attribute" because it tries to set up a default to a readonly field
```python
class IGradeBookEntry(IContainer,IContained):

    DueDate = Date(title="The date on which the assignment is due", 
                   required=False,
                   readonly=True)

@interface.implementer(IGradeBookEntry, IAttributeAnnotatable)
class GradeBookEntry(SchemaConfigured,
					 CheckingLastModifiedBTreeContainer,
					 Contained):
	createDirectFieldProperties(IGradeBookEntry)

ge  = GradeBookEntry()
```

Carlos

**Comment by papachoco** [comment]
We are using zope.interface-4.4.1 and zope.schema-4.4.2

**Comment by jamadden** [comment]
I don't understand how that could be happening. If you use `createDirectFieldProperties`, then the newly-created `self` *will* have a `DueDate` property already---it will be a FieldProperty object (stored on the class).

So I can't replicate this in a test. That is, this test passes:
```python
    def test_readonly(self):
        # https://github.com/NextThought/nti.schema/issues/11
        from nti.schema.fieldproperty import createDirectFieldProperties
        class IA(interface.Interface):
            field = Number(readonly=True,
                           required=False,
                           default=1)

        @interface.implementer(IA)
        class A(SchemaConfigured):
            createDirectFieldProperties(IA)

        a = A()
        assert_that(a, has_property('field', 1))
```

Can you provide more information? Maybe a traceback?

**Comment by papachoco** [comment]
```----------------------------------------------------------------------
Traceback (most recent call last):
  File "//sources/nti.app.products.gradebook/src/nti/app/products/gradebook/tests/test_grades.py", line 82, in test_wref
    column = grade.__parent__ = _GradeBookEntry()
  File "//sources/nti.app.products.gradebook/src/nti/app/products/gradebook/gradebook.py", line 187, in __init__
    SchemaConfigured.__init__(self, **kwargs)
  File "/eggs/nti.schema-1.1.3-py2.7.egg/nti/schema/schema.py", line 78, in __init__
    setattr(self, f, fields.default)
  File "//sources/nti.zodb/src/nti/zodb/persistentproperty.py", line 86, in __setattr__
    super(PersistentPropertyHolder, self).__setattr__(name, value)
AttributeError: can't set attribute
```
The constructor of the class calls  ```SchemaConfigured.__init__(self, **kwargs)```

**Comment by jamadden** [comment]
What's the output of `python -c "from XXX import GradeBookEntry; print(GradeBookEntry.__dict__)`?

**Comment by papachoco** [comment]
```python 
{
...
'Name': <property object at 0x10bf63520>,
'gradeScheme': <property object at 0x10bf635d0>, 
'AssignmentId': <zope.schema.fieldproperty.FieldProperty object at 0x10bf5c5d0>,
 'displayName': <zope.schema.fieldproperty.FieldProperty object at 0x10bf5c590>, 
'GradeScheme': <zope.schema.fieldproperty.FieldProperty object at 0x10bf5c550>, 
'assignmentId': <property object at 0x10bf63628>, 
'order': <zope.schema.fieldproperty.FieldProperty object at 0x10bf5c610>, 
'__parent__': <zope.schema.fieldproperty.FieldProperty object at 0x10bf5c4d0>, 
'DueDate': <property object at 0x10bf63730>, 
...
}
```

**Comment by jamadden** [comment]
OK, so there's a part of the class definition that got left out. Here's how it actually looks:
```python
@interface.implementer(IGradeBookEntry, IAttributeAnnotatable)
class GradeBookEntry(SchemaConfigured,
                     CheckingLastModifiedBTreeContainer,
                     Contained):
    createDirectFieldProperties(IGradeBookEntry)

    @property
    def DueDate(self):
          try:
               ...
          except (LookupError, TypeError):
              return None
```

In other words, the mutable field property for `DueDate` created by `createDirectFieldProperties` is completely overridden by the later definition of a standard, non-mutable `@property`.

The part that I elided with `...` in the `DueDate` property is doing some complicated things. On Python 2, `hasattr` ignores *all exceptions*, not just AttributeError---if any exception is raised, it returns False. So probably what's going on is that the complicated code in `DueDate` is raising an exception that's not caught, `hasattr` returns False, and we try to set the field.

I suggest debugging `DueDate` and seeing what exception is being raised, and you'll probably want to catch it (or avoid it) and return `None`.

We can also modify `SchemaConfigured` to use a custom `hasattr` implementation on Python 2 that won't ignore exceptions besides `AttributeError`; that's fairly commonly done to avoid this problem (for example, [transaction does it](https://github.com/zopefoundation/transaction/blob/master/transaction/_transaction.py#L48)).

**Comment by papachoco** [comment]
Thanks a los Jason
