### ISSUE TITLE
assert in FieldValidationMixin._reraise_validation_error 

### ISSUE THREAD

**Issue by papachoco** [NextThought/nti.schema#27]
Jason,

We are raising a ValidationError within a field constraint .. e.g.

```python   
description = ValidText(title=u'Biography',
                            description=u"A short overview of who you are and what you "
                            u"do. Will be displayed on your author page, linked "
                                        u"from the items you create.",
                            max_length=140,  # twitter
                                        required=False,
                            constraint=checkCannotBeBlank)
```

since we are reusing the constraint function for other interfaces we don't specified the 'field' in the actual validation error exception.  

line 173 in field.py

assert e.field is not None, "A _validate method failed to use ex.with_field_and_value()"

does not allow to reraise the error properly.

Could we relax this assertion?

Carlos

**Comment by jamadden** [comment]
I view that as a bug in `zope.schema`, it should be setting field and value on those exceptions. I'll open a PR there.

**Comment by papachoco** [comment]
I may have stated the problem incorrectly. We raise our own [generic] validation errors (during constraint checking) in field types that derive from the class nti.schema.field.FieldValidationMixin  (line 173 has the assert).  We don't specified the field when throwing the exception

I see that in Line 205 of nti.schema.field.py we don't set the field for the exception.

**Comment by jamadden** [comment]
Constraints are really supposed to return True/False, not raise exceptions...at least, they're not expected to. But there are good reasons for them to, and the _validate method that checks them should be prepared for this.

**Comment by papachoco** [comment]
This is legacy code in the dataserver in which exceptions are raised in constraints

**Comment by jamadden** [comment]
Yeah, and I think that's a case that makes sense to support. https://github.com/zopefoundation/zope.schema/issues/66

**Comment by jamadden** [comment]
zope.schema 4.6.2 has been released, which should close this issue.
