### ISSUE TITLE
Return nested schemas in JsonSchemafier

### ISSUE THREAD

**Issue by jzuech3** [NextThought/nti.schema#42]
Return nested item schemas in JsonSchemafier. Currently when building a schema, we'll return the item schema for a sequence type (e.g. ListOrTuple), but without the underlying schema information for the contained type.

**Comment by jamadden** [comment]
Prior to [zope.schema 4.6](https://zopeschema.readthedocs.io/en/latest/changelog.html#id7) there wasn't either a public super-class or guaranteed public interface exposing `value_type` (and `key_type` for mapping fields). Now that there is, this should be relatively easy.
