### ISSUE TITLE
Incorrect plurality in some cases for fields with min length

### ISSUE THREAD

**Issue by hagenrd** [NextThought/nti.schema#56]
When a field with a min length raises `TooShort` during validation, if the min length is 1, the plurality is incorrect, e.g. "Body is too short. Please use at least 1 characters."

**Comment by jamadden** [comment]
When that code was first written, `zope.i18nmessageid` didn't support plurals. Now it does, so we should be able to do something nicer than the DOS-ism "1 character(s)".
